//Teams
export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const LOAD_SEATING_CHART_SUCCESS = 'LOAD_SEATING_CHART_SUCCESS';

//Games
export const REQUEST_GAMES = 'REQUEST_GAMES';
export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const ADD_GAMES_SUCCESS = 'ADD_GAMES_SUCCESS';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';

//Tickets
export const REQUEST_TICKETS = 'REQUEST_TICKETS';
export const LOAD_TICKETS_SUCCESS = 'LOAD_TICKETS_SUCCESS';

//Sports
export const LOAD_SPORTS_SUCCESS = 'LOAD_SPORTS_SUCCESS';
export const CREATE_SPORT_SUCCESS = 'CREATE_SPORT_SUCCESS';

//venues
export const LOAD_VENUES_SUCCESS = 'LOAD_VENUES_SUCCESS';
export const CREATE_VENUE_SUCCESS = 'CREATE_VENUE_SUCCESS';

//Seating Charts
export const LOAD_SEATING_CHART = 'LOAD_SEATING_CHART';
export const LOAD_SEATING_CHART_CONFIGURATION = 'LOAD_SEATING_CHART_CONFIGURATION';

//Seeating Charts Sectoins
export const SEATING_CHART_SECTIONS_ADD = 'SEATING_CHART_SECTIONS_ADD';
export const SEATING_CHART_SECTIONS = 'SEATING_CHART_SECTIONS';

export const SELECT_SECTION = 'SELECT_SECTION';

//Loading
export const LOADING_STATES = 'LOADING_STATES';

//Users
export const ACTIVE_USERS = 'ACTIVE_USERS';
export const USER_ERROR = 'USER_ERROR';

//Settings
export const SETTINGS = 'SETTINGS';
export const REQUEST_SETTINGS = 'REQUEST_SETTINGS';
