//Teams
export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const LOAD_SEATING_CHART_SUCCESS = 'LOAD_SEATING_CHART_SUCCESS';

//Games
export const REQUEST_GAMES = 'REQUEST_GAMES';
export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const ADD_GAMES_SUCCESS = 'ADD_GAMES_SUCCESS';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';

//TicketListings
export const LOAD_TICKET_LISTINGS = 'LOAD_TICKET_LISTINGS';
export const SELECT_TICKET_LISTING = 'SELECT_TICKET_LISTING';
export const NEW_FILTER_TICKET_LISTINGS_BY_SECTION = 'NEW_FILTER_TICKET_LISTINGS_BY_SECTION';
export const HIDE_TICKET_LISTINGS_BY_SECTION = 'HIDE_TICKET_LISTINGS_BY_SECTION';
export const SHOW_TICKET_LISTINGS_BY_SECTION = 'SHOW_TICKET_LISTINGS_BY_SECTION';
export const CLEAR_TICKET_LISTINGS_FILTER = 'CLEAR_TICKET_LISTINGS_FILTER';
export const GET_TICKET_LISTING = 'GET_TICKET_LISTING';
export const ADD_TICKET_LISTING_TO_CART = 'ADD_TICKET_LISTING_TO_CART';

//Tickets
export const LOAD_TICKETS_SUCCESS = 'LOAD_TICKETS_SUCCESS';
export const NEW_FILTER_TICKETS_FROM_SECTION = 'NEW_FILTER_TICKETS_FROM_SECTION';
export const HIDE_TICKETS_FROM_SECTION = 'HIDE_TICKETS_FROM_SECTION';
export const SHOW_TICKETS_FROM_SECTION = 'SHOW_TICKETS_FROM_SECTION';
export const CLEAR_FILTER = 'CLEAR_FILTER';

//Sports
export const LOAD_SPORTS_SUCCESS = 'LOAD_SPORTS_SUCCESS';
export const CREATE_SPORT_SUCCESS = 'CREATE_SPORT_SUCCESS';

//venues
export const LOAD_VENUES_SUCCESS = 'LOAD_VENUES_SUCCESS';
export const CREATE_VENUE_SUCCESS = 'CREATE_VENUE_SUCCESS';

//Seating Charts
export const LOAD_SEATING_CHART = 'LOAD_SEATING_CHART';
export const LOAD_SEATING_CHART_CONFIGURATION = 'LOAD_SEATING_CHART_CONFIGURATION';

//Seeating Charts Sections
export const SEATING_CHART_SECTIONS_ADD = 'SEATING_CHART_SECTIONS_ADD';
export const SEATING_CHART_SECTIONS = 'SEATING_CHART_SECTIONS';

export const SELECT_SECTION = 'SELECT_SECTION';
export const CLEAR_SELECTIONS = 'CLEAR_SELECTIONS';


//Loading
export const LOADING_STATES = 'LOADING_STATES';

//Messages
export const ADD_MESSAGE = 'ADD_MESSAGE';

//Users
export const ACTIVE_USERS = 'ACTIVE_USERS';
export const USER_ERROR = 'USER_ERROR';
export const LOADED_USER = 'LOADED_USER';

//Settings
export const SETTINGS = 'SETTINGS';
export const REQUEST_SETTINGS = 'REQUEST_SETTINGS';
export const SET_REDIRECT = 'SET_REDIRECT';
